image: php:7.2

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: test_db
  MYSQL_USER: test_user
  MYSQL_PASSWORD: password
stages:
  - build
  - testing
  # - staging
  # - deployment

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY # allow this to push built container to gitlab registry

build_containers:
  image: docker/compose:latest
  stage: build
  script:
    - cd build
    - docker-compose -f docker-compose.gitlab.yml build 
    - docker-compose push # need to figure out how to push here (how to get credentials)

unit_testing:
  stage: testing
  script:
    - bash ci/scripts/unit_testing.sh

# deploy_production:  
#   stage: deployment
#   script:
#     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$SSH_PRIVATE_KEY")
#     - mkdir -p ~/.ssh
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#     - ~/.composer/vendor/bin/envoy run deploy
#   environment:
#     name: production
#     url: http://192.168.1.1
#   when: manual
#   only:
#     - master