variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: test_db
  MYSQL_USER: test_user
  MYSQL_PASSWORD: password
  
stages:
  - testing
  - deployment

# before_script:
#   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY # allow this to push built container to gitlab registry

# build_containers:
#   image: docker/compose:latest
#   stage: build
#   script:
#     - cd build
#     - docker-compose -f docker-compose.gitlab.yml build 
#     - docker-compose push # need to figure out how to push here (how to get credentials)

unit_testing:
  stage: testing
  image: php:7.2
  before_script:
    - bash ci/scripts/before.sh
  services:
    - mysql:5.7
    - redis:5.0.0-alpine
  script:
    - bash ci/scripts/unit_testing.sh

deploy_production:  
  stage: deployment
  image: php:7.2
  before_script:
    - bash ci/scripts/before.sh
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - cd test-app/ && ~/.composer/vendor/bin/envoy run deploy --IP=34.230.63.70
  environment:
    name: production
    url: http://34.230.63.70
  when: manual
  only:
    - master